-- DV SOUND & DJ KUKMA — production review + admin setup
-- Run this in Supabase SQL Editor.
-- No artificial review-count limit is imposed by this schema.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  rating integer not null check (rating between 1 and 5),
  review text not null check (char_length(review) between 1 and 1000),
  approved boolean not null default false,
  status text not null default 'pending',
  approved_at timestamptz,
  approved_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint reviews_status_check check (status in ('pending','approved','rejected'))
);

-- Safe migration for the earlier version of this project.
alter table public.reviews add column if not exists status text;
alter table public.reviews add column if not exists approved_at timestamptz;
alter table public.reviews add column if not exists approved_by uuid references auth.users(id);

update public.reviews
set status = case when coalesce(approved,false) then 'approved' else 'pending' end
where status is null;

alter table public.reviews alter column status set default 'pending';

create index if not exists reviews_status_created_at_idx
  on public.reviews (status, created_at desc);
create index if not exists reviews_created_at_idx
  on public.reviews (created_at desc);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Public can read approved reviews" on public.reviews;
drop policy if exists "Public can submit reviews" on public.reviews;
drop policy if exists "Admins can read all reviews" on public.reviews;
drop policy if exists "Admins can update reviews" on public.reviews;
drop policy if exists "Admins can delete reviews" on public.reviews;

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_current_user_admin() from public;
grant execute on function public.is_current_user_admin() to authenticated;

create policy "Public can read approved reviews"
on public.reviews for select
to anon, authenticated
using (status = 'approved' or public.is_current_user_admin());

create policy "Public can submit reviews"
on public.reviews for insert
to anon, authenticated
with check (status = 'pending' and approved = false and approved_at is null and approved_by is null);

create policy "Admins can update reviews"
on public.reviews for update
to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy "Admins can delete reviews"
on public.reviews for delete
to authenticated
using (public.is_current_user_admin());

-- Admin moderation function: only users explicitly placed in admin_users can approve/reject.
create or replace function public.moderate_review(review_id bigint, new_status text)
returns public.reviews
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.reviews;
begin
  if not public.is_current_user_admin() then
    raise exception 'Not authorised as an admin';
  end if;

  if new_status not in ('approved','rejected') then
    raise exception 'Invalid moderation status';
  end if;

  update public.reviews
     set status = new_status,
         approved = (new_status = 'approved'),
         approved_at = case when new_status = 'approved' then now() else null end,
         approved_by = case when new_status = 'approved' then auth.uid() else null end
   where id = review_id
   returning * into result;

  if result.id is null then raise exception 'Review not found'; end if;
  return result;
end;
$$;

revoke all on function public.moderate_review(bigint,text) from public;
grant execute on function public.moderate_review(bigint,text) to authenticated;

-- Public website gets average/count across ALL approved reviews, not just the 50 displayed.
create or replace function public.get_review_stats()
returns table (average_rating numeric, review_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(round(avg(rating)::numeric, 1), 0), count(*)
  from public.reviews
  where status = 'approved';
$$;

revoke all on function public.get_review_stats() from public;
grant execute on function public.get_review_stats() to anon, authenticated;


-- Admin-only permanent deletion. Use this from the admin dashboard if preferred.
create or replace function public.delete_review(review_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_current_user_admin() then
    raise exception 'Not authorised as an admin';
  end if;
  delete from public.reviews where id = review_id;
end;
$$;

revoke all on function public.delete_review(bigint) from public;
grant execute on function public.delete_review(bigint) to authenticated;

-- First admin setup:
-- 1) Supabase Dashboard -> Authentication -> Users -> create the owner's email/password user.
-- 2) Copy that user's UUID.
-- 3) Run: insert into public.admin_users(user_id) values ('OWNER-USER-UUID');
